### ISSUE TITLE
Didn't work user recent items, work only popular images!

### ISSUE THREAD

**Issue by andryshok** [suhindra/CodeIgniter3-Instagram-API#1]
A PHP Error was encountered

A PHP Error was encountered

Severity: Notice

Message: Trying to get property of non-object

Filename: views/user_recent.php

Line Number: 3

Backtrace:

File: /home/user1174182/www/test.amweb.by/application/views/user_recent.php
Line: 3
Function: _error_handler

File: /home/user1174182/www/test.amweb.by/application/views/template.php
Line: 85
Function: view

File: /home/user1174182/www/test.amweb.by/application/controllers/User.php
Line: 70
Function: view

File: /home/user1174182/www/test.amweb.by/index.php
Line: 292
Function: require_once

**Comment by suhindra** [comment]
have you ever posted picture using your instagram? because it work on mine,

**Comment by suhindra** [comment]
have you ever posted the picture using your instagram? because it working on mine

**Comment by andryshok** [comment]
I already wrote the code, yours is irrelevant and disabled. If I tried library respectively I know as to work with instagram.

**Comment by suhindra** [comment]
So error in demo code or in library code?
